from chibi.atlas import Chibi_atlas


boards = Chibi_atlas( {
    "a": "Anime and Manga",
    "c": "Anime/Cute",
    "w": "Anime/Wallpapers",
    "m": "Mecha",
    "cgl": "Cosplay and EGL",
    "cm": "Cute/Male",
    "f": "Flash",
    "n": "Transportation",
    "jp": "Otaku Culture",
    "vp": "Pokemon",

    "v": "Video Games",
    "vg": "Video Game Generals",
    "vr": "Retro Games",
    "co": "Comics & Cartoons",
    "g": "Technology",
    "tv": "Television & Film",
    "k": "Weapons",
    "o": "Auto",
    "an": "Animals & Nature",
    "tg": "Traditional Games",
    "qst": "Quests",
    "sp": "Sports",
    "asp": "Alternative Sports",
    "sci": "Science & Math",
    "int": "International",
    "out": "Outdoors",
    "toy": "Toys",
    "biz": "Business & Finance",

    "i": "Oekaki",
    "po": "Papercraft & Origami",
    "p": "Photography",
    "ck": "Food & Cooking",
    "ic": "Artwork/Critique",
    "wg": "Wallpapers/General",
    "mu": "Music",
    "fa": "Fashion",
    "3": "3DCG",
    "gd": "Graphic Design",
    "diy": "Do-It-Yourself",
    "wsg": "Worksafe GIF",

    "s": "Beautiful Women",
    "hc": "Hardcore",
    "hm": "Handsome Men",
    "h": "Hentai",
    "e": "Ecchi",
    "u": "Yuri",
    "d": "Hentai/Alternative",
    "y": "Yaoi",
    "t": "Torrents",
    "hr": "High Resolution",
    "gif": "Adult GIF",

    "trv": "Travel",
    "fit": "Fitness",
    "x": "Paranormal",
    "lit": "Literature",
    "adv": "Advice",
    "lgbt": "LGBT",
    "mlp": "Pony [see My Little Pony]",

    "b": "Random",
    "r": "Request",
    "r9k": "ROBOT9001",
    "pol": "Politically Incorrect",
    "soc": "Cams & Meetups",
    "s4s": "Shit 4chan Says",
} )
